[package]
name = "pubky-nexus"
version = "0.3.1"
edition = "2021"
description = "Nexus between homeservers and Pubky-App. Pubky-nexus constructs a social graph out of all of the events on pubky-core homeservers and exposes a social-media-like API capable of powerful Web-of-Trust inference."
homepage = "https://github.com/pubky"
repository = "https://github.com/pubky/pubky-nexus"
license = "MIT"
#default-run = "service"
build = "build.rs"

[dependencies]
async-trait = "0.1.85"
axum = "0.8.1"
chrono = { version = "0.4.39", default-features = false, features = ["clock"] }
clap = { version = "4.5.29", features = ["derive"] }
const_format = "0.2.34"
dotenv = "0.15"
neo4rs = "0.8.0"
once_cell = "1.20.2"
opentelemetry = { version = "0.28" }
opentelemetry-appender-tracing = "0.28.1"
opentelemetry-otlp = { version = "0.28", features = ["grpc-tonic"] }
opentelemetry-stdout = { version = "0.28" }
opentelemetry_sdk = { version = "0.28", features = ["rt-tokio"] }
pubky = "0.4.1"
pubky-app-specs = { version = "0.3.2", features = ["openapi"] }
pubky-testnet = "0.1.1"
redis = { version = "0.29.0", features = ["tokio-comp", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["full"] }
toml = "0.8.20"
tower-http = { version = "0.6.2", features = ["fs", "cors"] }
tracing = "0.1"
tracing-opentelemetry = "0.29"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = "5.3.1"
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }

[dev-dependencies]
anyhow = "1.0.95"
httpc-test = "0.1.10"
criterion = { version = "0.5.1", features = ["async_tokio"] }
pubky-homeserver = "0.1.1"
rand = "0.8.5"
rand_distr = "0.4.3"
tokio-shared-rt = "0.1"
url = "2.5.4"
reqwest = "0.12.12"

[lib]
name = "pubky_nexus"
path = "src/lib.rs"

# [[bin]]
# name = "service"
# path = "src/service.rs"

# [[bin]]
# name = "watcher"
# path = "src/watcher.rs"

# [[bin]]
# name = "migrations"
# path = "src/migrations.rs"

# [[bin]]
# name = "mockdb"
# path = "src/mock_db.rs"

# [[bench]]
# name = "user"
# harness = false

# [[bench]]
# name = "tag"
# harness = false

# [[bench]]
# name = "post"
# harness = false

# [[bench]]
# name = "reindex"
# harness = false

# [[bench]]
# name = "follows"
# harness = false

# [[bench]]
# name = "streams"
# harness = false

# [[bench]]
# name = "search"
# harness = false

# [[bench]]
# name = "watcher"
# harness = false

# Max performance profile
[profile.release]
opt-level = 3
codegen-units = 1
lto = true
incremental = false
