# List migrations that are in the "backfill_ready" state and should be processed.
# Add migration IDs here when they are ready for backfilling. Example
#backfill_ready = ["Xakala1741101644"]
backfill_ready = []

[stack]
name = "nexus.migration"
# Logging, options: error, warn, info, debug and trace
log_level = "debug"
files_path = "./static/files"
# OTLP_ENDPOINT is set to empty by default. If you want to enable tracing, set it to the OpenTelemetry Collector endpoint
#otlp_endpoint=""

[stack.db]
redis = "redis://localhost:6379"

[stack.db.neo4j]
uri = "bolt://localhost:7687"
# Not need it. Might be default
user = "neo4j"
password = "12345678"