# Service name used for tracing, logging, and metrics in OpenTelemetry
name = "nexus.example.watcher"
testnet = false
homeserver = "8um71us3fyw6h8wbcxb5ar3rwusy1a6u49956ikzojg3gcwd1dty"
events_limit = 50
watcher_sleep = 5000

[stack]
# Logging, options: error, warn, info, debug and trace
log_level = "debug"
files_path = "./examples/static/files"
# OTLP_ENDPOINT is set to empty by default. If you want to enable tracing, set it to the OpenTelemetry Collector endpoint
#otlp_endpoint="http://localhost:4317"

[stack.db]
redis = "redis://localhost:6379"

[stack.db.neo4j]
uri = "bolt://localhost:7687"
# Not needed in the Community Edition
#user = "neo4j"
password = "12345678"