#!/usr/bin/env bash
#
# Graph query performance audit: runner.
#
# Profiles every audited query at two scales (large = 10x small) and writes a
# markdown report sorted by growth factor. A query whose db hits grow much
# faster than the data (>10x) is super-linear in some dimension and gets flagged
# REVIEW. PROFILE db hits are the ground truth; exec_ms is informational.
#
# Usage:  ./run.sh [output.md]      (default: docker/bench-graph/report.md)
# Needs:  the dockerised neo4j running (docker compose up), nothing seeded.
set -euo pipefail
cd "$(dirname "$0")/../.."   # repo root

PASS="${NEO4J_PASSWORD:-12345678}"
OUT="${1:-docker/bench-graph/report.md}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

profile() { docker exec -i neo4j cypher-shell -u neo4j -p "$PASS" --format verbose 2>&1; }

echo "building dumper..."
cargo build -q -p nexus-examples --bin graph-audit
DUMP="$TMP/queries.txt"
./target/debug/graph-audit > "$DUMP"
echo "audited queries: $(grep -c '@@QUERY' "$DUMP")"

# Profile every dumped block against the currently-seeded graph -> label<TAB>dbhits<TAB>ms
profile_scale() {
  local scale="$1"
  local res="$TMP/$scale.tsv" label="" buf=""
  : > "$res"
  echo "  seeding $scale..."; bash docker/bench-graph/seed.sh "$scale" >/dev/null
  echo "  profiling $scale..."
  while IFS= read -r line; do
    case "$line" in
      @@QUERY*) label="${line#@@QUERY }"; buf="" ;;
      @@END)
        local out dbh ms
        out="$(printf '%s\n' "$buf" | profile)"
        dbh="$(grep -oP 'Total database accesses: \K[0-9]+' <<<"$out" | head -1)"
        ms="$(grep -oP 'results consumed after another \K[0-9]+' <<<"$out" | head -1)"
        printf '%s\t%s\t%s\n' "$label" "${dbh:-NA}" "${ms:-NA}" >> "$res"
        ;;
      *) buf+="$line"$'\n' ;;
    esac
  done < "$DUMP"
}

profile_scale small
profile_scale large
bash docker/bench-graph/seed.sh clean >/dev/null

# Join small+large by label, compute growth, sort worst-first.
ROWS="$TMP/rows"; : > "$ROWS"
while IFS=$'\t' read -r label sdbh sms; do
  ldata="$(grep -P "^${label}\t" "$TMP/large.tsv" || true)"
  ldbh="$(cut -f2 <<<"$ldata")"; lms="$(cut -f3 <<<"$ldata")"
  growth="NA"; gkey="-1"; flag=""
  if [[ "$sdbh" =~ ^[0-9]+$ && "$ldbh" =~ ^[0-9]+$ && "$sdbh" -gt 0 ]]; then
    growth="$(awk -v a="$sdbh" -v b="$ldbh" 'BEGIN{printf "%.1f", b/a}')"
    gkey="$growth"
    awk -v g="$growth" 'BEGIN{exit !(g>15)}' && flag="**REVIEW**"
  fi
  printf '%s\t| %s | %s | %s | %sx | %s | %s |\n' "$gkey" "$label" "$sdbh" "$ldbh" "$growth" "$lms" "$flag" >> "$ROWS"
done < "$TMP/small.tsv"

{
  echo "# Graph query performance audit"
  echo
  echo "Generated by \`docker/bench-graph/run.sh\`. Each query profiled at two scales"
  echo "(large = 10x small). Numbers are PROFILE \`Total database accesses\` (db hits);"
  echo "\`exec_ms L\` is server-side execution at large scale (informational)."
  echo
  echo "**growth** = dbhits(large) / dbhits(small). ~10x = linear in the scaled"
  echo "dimension (expected). **>10x is super-linear** and flagged REVIEW: the query"
  echo "does work proportional to a *product* of dimensions."
  echo
  echo "| query | dbhits S | dbhits L | growth | exec_ms L | flag |"
  echo "|---|--:|--:|--:|--:|---|"
  sort -t$'\t' -k1 -rn "$ROWS" | cut -f2-
} | tee "$OUT"

echo "report written to $OUT"
