name: Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          profile: minimal
          components: rustfmt, clippy
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install dependencies
        run: cargo build --release

      - name: Copy environment variables
        run: cp .env-sample .env

      - name: Set up Docker Compose
        working-directory: docker
        run: docker compose --env-file .env-sample up -d

      - name: Wait for services to be ready
        run: |
          until curl -sS http://localhost:7474; do
            echo "Waiting for Neo4j to be ready..."
            sleep 1
          done
          until nc -zv 127.0.0.1 6379; do
            echo "Waiting for Redis to be ready..."
            sleep 1
          done

      - name: Create example graph
        run: docker exec neo4j bash /db-migration/run-queries.sh

      - name: Run the service
        run: ./target/release/service &

      - name: Run tests
        run: cargo test

      - name: Run clippy
        run: cargo clippy -- -D warnings # Fail on clippy warnings

      - name: Run cargo fmt
        run: cargo fmt -- --check # Fail if code is not formatted

      - name: Tear down Docker Compose
        if: always()
        working-directory: docker
        run: docker-compose down --volumes
